// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Runtime;
using UnityEngine;
using System.Collections;
using System.Runtime.InteropServices;

public class GameNetMessage
{
	public enum MsgType
	{
		GMT_LOGIN = 1000,

		GMT_HEART = 10005,
	};


	[ System.Serializable ]
	[ StructLayout( LayoutKind.Sequential , Pack = 1 ) ]
	public class NetMsgHead
	{
		public short size;
		public short type;
		
		public NetMsgHead()
		{
			size = 0;
			type = 0;
		}
		
	};  

	[ System.Serializable ]
	[ StructLayout( LayoutKind.Sequential , Pack = 1 ) ]
	public class NetMsgHeart : NetMsgHead
	{
//		[ MarshalAs( UnmanagedType.ByValArray, SizeConst = 2 ) ]
//		public int[] n = new int[ 2 ];
//		
//		
		public int n = 11;
//		[ MarshalAs( UnmanagedType.ByValTStr , SizeConst = 32 ) ]
//		public string name;

		public NetMsgHeart()
		{
			size = (short)Marshal.SizeOf( typeof( GameNetMessage.NetMsgHeart ) );
			type = (short)MsgType.GMT_HEART;
		}
		
	}

	[ System.Serializable ]
	[ StructLayout( LayoutKind.Sequential , Pack = 1 ) ]
	public class NetMsgLogin : NetMsgHead
	{
		public char count;

		[ MarshalAs( UnmanagedType.ByValTStr , SizeConst = 32 ) ]
		public NetMsgHead[] n1 ;


		public NetMsgLogin()
		{
			size = (short)Marshal.SizeOf( typeof( GameNetMessage.NetMsgLogin ) );
			type = (short)MsgType.GMT_LOGIN;
		}

	}


}